### ISSUE TITLE
Setting unknown property: swoole\foundation\web\Server::id

### ISSUE THREAD

**Issue by myz123126** [swoole-foundation/yii2-swoole-extension#6]
there is a problem.

// config/swoole.php
PHP Fatal error:  Uncaught yii\base\UnknownPropertyException: Setting unknown property: swoole\foundation\web\Server::id in /home/www/miniMarket/vendor/yiisoft/yii2/base/BaseObject.php:162
Stack trace:
#0 /home/www/miniMarket/vendor/yiisoft/yii2/BaseYii.php(532): yii\base\BaseObject->__set()
#1 /home/www/miniMarket/vendor/yiisoft/yii2/base/BaseObject.php(106): yii\BaseYii::configure()
#2 /home/www/miniMarket/index.php(19): yii\base\BaseObject->__construct()
#3 {main}

**Comment by myz123126** [comment]
its solved
i update the yii2
